#!/bin/bash

#DEBHELPER#

# preinst script for grub-files-mx

#set -e

case "$1" in
  install|upgrade) \
    ##preseed debconf to enable os-prober
    if [ -z "$(debconf-get-selections |grep grub-files-mx)" ]; then
        echo "grub-files-mx grub2/grub_files_mx_enable_os_prober boolean true" | debconf-set-selections
        echo "set up os-prober"
        echo "grub-pc grub2/enable_os_prober boolean true" | debconf-set-selections
    fi
    for F in \
        /etc/grub.d/00_header    \
        /etc/grub.d/05_debian_theme    \
        /etc/grub.d/10_linux    \
        /etc/grub.d/20_linux_xen    \
        /etc/grub.d/20_memtest86+   \
        /etc/grub.d/30_os-prober    \
        /etc/grub.d/30_uefi-firmware    \
        /etc/grub.d/40_custom    \
        /etc/grub.d/41_custom    \
        /usr/share/grub/default/grub \
        /etc/grub.d/README
    do
        dpkg-divert --quiet --package grub-files-mx --rename \
                    --divert $F.dpkg-dist --add $F || :
    done
  ;;
  *) :
  ;;

esac

exit 0
