#!/bin/bash

#DEBHELPER#

# preinst script for grub-files-mx

#set -e

case "$1" in
  install|upgrade) \
    ##preseed debconf to enable os-prober
    if [ -z "$(debconf-get-selections |grep grub-files-mx)" ]; then
        echo "grub-files-mx grub2/grub_files_mx_enable_os_prober boolean true" | debconf-set-selections
        echo "set up os-prober"
        echo "grub-pc grub2/enable_os_prober boolean true" | debconf-set-selections
    fi
    #make sure a directory exists
    mkdir -p /var/lib/dpkg-diverts-mx/etc/grub.d /var/lib/dpkg-diverts-mx/usr/share/grub/default/
    for F in \
        /etc/grub.d/00_header    \
        /etc/grub.d/05_debian_theme    \
        /etc/grub.d/10_linux    \
        /etc/grub.d/20_linux_xen    \
        /etc/grub.d/20_memtest86+   \
        /etc/grub.d/30_os-prober    \
        /etc/grub.d/30_uefi-firmware    \
        /etc/grub.d/40_custom    \
        /etc/grub.d/41_custom    \
        /usr/share/grub/default/grub \
        /etc/grub.d/README
    do
        # cleanup past installs
        if [ -n $(dpkg-divert --list \"/etc/grub.d/$F.dpkg-dist\") ]; then 
        	dpkg-divert --package grub-files-mx --no-rename --divert $F.dpkg-dist --remove $F
        fi

    	if [ -e $F.dpkg-dist.dpkg-dist ]; then
    		mv -f $F.dpkg-dist.dpkg-dist /var/lib/dpkg-diverts-mx$F
    	fi
    	
    	if [ -e $F.dpkg-dist ]; then
    		mv -f $F.dpkg-dist /var/lib/dpkg-diverts-mx$F
    	fi
  
    	#new divert
        dpkg-divert --quiet --no-rename --package grub-files-mx  \
                    --divert /var/lib/dpkg-diverts-mx$F --add $F || :
    done
  ;;
  *) :
  ;;

esac

exit 0
